anthropic:
  model: claude-3-5-sonnet-20241022
  max_tokens: 4096
  temperature: 0.7

ollama:
  base_url: http://localhost:11434
  embedding_model: nomic-embed-text
  chat_model: llama3.1
  temperature: 0.7
  timeout: 120

crawler:
  max_depth: 3
  max_pages: 100
  delay_between_requests: 1.0
  respect_robots_txt: true
  timeout: 30
  user_agent: AgentX-Crawler/1.0

vectordb:
  persist_directory: ./data/chroma
  chunk_size: 512
  chunk_overlap: 50

reranking:
  enabled: true
  initial_retrieval_k: 20
  final_top_k: 5

mcp_server:
  host: localhost
  port: 8001

api:
  host: 0.0.0.0
  port: 8000
  cors_origins:
    - http://localhost:3000
  log_level: info
